const AUTHENTICATED = "AUTHENTICATED";
const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";
const ERROR_AUTHENTICATE = "ERROR_AUTHENTICATE";

export {
    AUTHENTICATED,
    ERROR_AUTHENTICATE,
    NOT_AUTHENTICATED
}
